version: '3'

services:
  mysql:
    container_name: zitro-test-mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  nginx:
    container_name: zitro-test-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8040:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: zitro-test-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql